// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nseqrdoqbydvslbvdgvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZXFyZG9xYnlkdnNsYnZkZ3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTY2NzEsImV4cCI6MjA3MzUzMjY3MX0.N3ftGuQQod7Nwi1rAN72VMFgkz4mUwAw7Gcr_t8z99o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});